import { IsString, IsNotEmpty, IsOptional, IsEmail, IsArray, IsEnum } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { AdminRoles } from 'src/common/enums/user.enum';

export class AdminUserDto {
  @ApiProperty({
    description: 'Admin ID (auto-generated)',
    example: 'admin_123456789',
    required: false
  })
  @IsString()
  @IsOptional() // Optional for creation, as it's generated by nanoid
  adminId?: string;

  @ApiProperty({
    description: 'Admin first name',
    example: 'John'
  })
  @IsString()
  @IsNotEmpty({ message: 'First name is required' })
  firstName: string;

  @ApiProperty({
    description: 'Admin last name',
    example: 'Doe'
  })
  @IsString()
  @IsNotEmpty({ message: 'Last name is required' })
  lastName: string;

  @ApiProperty({
    description: 'Admin email address',
    example: 'admin@company.com'
  })
  @IsEmail({}, { message: 'Please provide a valid email address' })
  @IsNotEmpty({ message: 'Email is required' })
  email: string;

  @ApiProperty({
    description: 'Admin phone number',
    example: '+1234567890',
    required: false
  })
  @IsString()
  @IsOptional()
  phoneNumber?: string;

  @ApiProperty({
    description: 'Admin role',
    enum: AdminRoles,
    example: AdminRoles.ADMIN,
    required: false
  })
  @IsEnum(AdminRoles, { message: 'Invalid admin role' })
  @IsOptional()
  role?: AdminRoles;

  @ApiProperty({
    description: 'Admin abilities and permissions',
    required: false,
    type: 'array',
    items: {
      type: 'object',
      properties: {
        attributeName: { type: 'string' },
        attributeAccess: { type: 'array', items: { type: 'string' } }
      }
    }
  })
  @IsOptional()
  @IsArray()
  abilities?: {
    attributeName: string;
    attributeAccess: string[];
  }[];
}