import { UserStatus, ReferrerMedium } from "../enums/user.enum";
export interface IUsers {
    userId: string;
    phoneNumber: string;
    email?: string;
    password?: string;
    userName?: string;
    Name?: string;
    name?: string;
    isVerified: boolean;
    isDeleted: boolean;
    otp?: string;
    otpExpiry?: Date;
    lastLoginAt?: Date;
    status: UserStatus;
    phoneVerified: boolean;
    phoneOtp?: string;
    phoneOtpExpiry?: Date;
    userNameSet: boolean;
    emailVerified: boolean;
    emailOtp?: string;
    emailOtpExpiry?: Date;
    expiresAt?: Date;
    referredBy?: string;
    referrerId?: string;
    referrerMedium?: ReferrerMedium;
    institutionsId?: string;
    departmentsId?: string;
    qrAuth?: boolean;
    isReferralVerified?: boolean;
    profileImage?: string;
    profileImageUpdatedAt?: Date;
    customLogin?: boolean;
    showPhoneNumber?: boolean;
    muteNotifications?: boolean;
    disableReadReceipt?: boolean;
    deviceId?: string;
    metaData?: {
        institutionId?: string;
    };
    createdAt?: Date;
    updatedAt?: Date;
    referralCode?: string;
}
