import { ReferrerMedium } from "../enums/user.enum";
export interface IUsers {
    userId: string;
    phoneNumber: string;
    email?: string;
    password?: string;
    userName?: string;
    Name?: string;
    isActive: boolean;
    isVerified: boolean;
    isDeleted: boolean;
    otp?: string;
    otpExpiry?: Date;
    lastLoginAt?: Date;
    status: string;
    phoneVerified: boolean;
    phoneOtp?: string;
    phoneOtpExpiry?: Date;
    userNameSet: boolean;
    emailVerified: boolean;
    emailOtp?: string;
    emailOtpExpiry?: Date;
    expiresAt?: Date;
    referredBy?: string;
    referrerId?: string;
    referrerMedium?: ReferrerMedium;
    qrAuth?: boolean;
    mutualfriendReferral?: boolean;
    profileImage?: string;
    profileImageUpdatedAt?: Date;
    createdAt?: Date;
    updatedAt?: Date;
}
